from setuptools import setup

setup(
    name='TItanic DS',
    version='development 1',
    packages=['venv.lib.python3.6.site-packages.bs4', 'venv.lib.python3.6.site-packages.bs4.tests',
              'venv.lib.python3.6.site-packages.bs4.builder', 'venv.lib.python3.6.site-packages.get',
              'venv.lib.python3.6.site-packages.post', 'venv.lib.python3.6.site-packages.csv23',
              'venv.lib.python3.6.site-packages.public', 'venv.lib.python3.6.site-packages.request',
              'venv.lib.python3.6.site-packages.urllib3', 'venv.lib.python3.6.site-packages.urllib3.util',
              'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.openpyxl', 'venv.lib.python3.6.site-packages.openpyxl.xml',
              'venv.lib.python3.6.site-packages.openpyxl.cell', 'venv.lib.python3.6.site-packages.openpyxl.chart',
              'venv.lib.python3.6.site-packages.openpyxl.pivot', 'venv.lib.python3.6.site-packages.openpyxl.utils',
              'venv.lib.python3.6.site-packages.openpyxl.compat', 'venv.lib.python3.6.site-packages.openpyxl.reader',
              'venv.lib.python3.6.site-packages.openpyxl.styles', 'venv.lib.python3.6.site-packages.openpyxl.writer',
              'venv.lib.python3.6.site-packages.openpyxl.drawing', 'venv.lib.python3.6.site-packages.openpyxl.formula',
              'venv.lib.python3.6.site-packages.openpyxl.comments',
              'venv.lib.python3.6.site-packages.openpyxl.workbook',
              'venv.lib.python3.6.site-packages.openpyxl.workbook.external_link',
              'venv.lib.python3.6.site-packages.openpyxl.packaging',
              'venv.lib.python3.6.site-packages.openpyxl.worksheet',
              'venv.lib.python3.6.site-packages.openpyxl.chartsheet',
              'venv.lib.python3.6.site-packages.openpyxl.formatting',
              'venv.lib.python3.6.site-packages.openpyxl.descriptors', 'venv.lib.python3.6.site-packages.et_xmlfile',
              'venv.lib.python3.6.site-packages.et_xmlfile.tests', 'venv.lib.python3.6.site-packages.query_string',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.req',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.vcs',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.utils',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.compat',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.models',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.commands',
              'venv.lib.python3.6.site-packages.pip-9.0.1-py3.6.egg.pip.operations'],
    url='',
    license='apache 2.0 Open Source',
    author='harkishen',
    author_email='harkishensingh@hotmail.com',
    description='Data Science Project'
)
